# Generated by Django 3.1.1 on 2021-04-15 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_organisations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expereions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Title', models.CharField(max_length=50, null=True)),
                ('Organisation', models.CharField(max_length=50, null=True)),
                ('Duration', models.DurationField(max_length=50, null=True)),
                ('From_Date', models.DateField()),
                ('To_Date', models.DateField()),
                ('Country', django_countries.fields.CountryField(max_length=2)),
                ('Location', models.CharField(max_length=50, null=True)),
                ('Responsibilities', models.TextField(help_text='Input your Exp', null=True)),
                ('city_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.city')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cours_Name', models.CharField(max_length=50, null=True)),
                ('Company', models.CharField(max_length=50, null=True)),
                ('Type', models.CharField(max_length=50, null=True)),
                ('Country', django_countries.fields.CountryField(max_length=2)),
                ('race_start', models.DateTimeField()),
                ('race_finish', models.DateTimeField(blank=True, null=True)),
                ('city_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.city')),
            ],
        ),
    ]
