# Generated by Django 3.1.1 on 2021-04-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_academic_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_background',
            name='Certificate_Type',
            field=models.CharField(choices=[(' High School', ' High School'), ('University student', 'University student'), ('diploma', 'diploma'), ('Intermediate Institute ', 'Intermediate Institute '), ("Bachelor's ", "Bachelor's "), ("Master's ", "Master's "), ('Ph.D.', 'Ph.D.')], max_length=50),
        ),
    ]
