# Generated by Django 3.1.1 on 2021-04-26 11:01

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210419_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normal_users',
            name='Birth_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='normal_users',
            name='Country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='normal_users',
            name='First_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='normal_users',
            name='Gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='normal_users',
            name='Last_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='normal_users',
            name='Midle_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='normal_users',
            name='Phone_Number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='normal_users',
            name='Photo',
            field=models.ImageField(blank=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='normal_users',
            name='Soical_State',
            field=models.CharField(blank=True, choices=[('single', 'single'), ('Married', 'Married'), ('divorced', 'divorced'), ('widowed', 'widowed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='normal_users',
            name='city_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.city'),
        ),
    ]
