# Generated by Django 3.1.1 on 2021-04-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210426_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normal_users',
            name='Photo',
            field=models.ImageField(default='profile/person.jpg', null=True, upload_to='profile/'),
        ),
    ]
