# Generated by Django 3.1.1 on 2021-05-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210426_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisations',
            name='About',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
