# Generated by Django 3.1.1 on 2021-05-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_organisations_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisations',
            name='slugan',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
