# Generated by Django 3.1 on 2021-05-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210517_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default-img/blog-def-img.png', upload_to='blog-img/'),
        ),
    ]
