# Generated by Django 3.1 on 2021-05-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210517_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog-img/blog-def-img.png', null=True, upload_to='blog-img/'),
        ),
    ]
