# Generated by Django 3.1 on 2021-05-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210517_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Hyper_Text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog-img/blog-def-img.png', null=True, upload_to='blog-img/'),
        ),
    ]
