# Generated by Django 3.1.1 on 2021-05-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210524_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
