# Generated by Django 3.1.1 on 2021-05-20 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_dead_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='last_Update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='descripyion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
