# Generated by Django 3.1.1 on 2021-05-20 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20210520_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='created_at',
        ),
        migrations.AddField(
            model_name='apply',
            name='last_Update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
