# Generated by Django 3.1.1 on 2021-05-20 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_apply_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='cover_leteer',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='email',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='last_Update',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='name',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='websit',
        ),
    ]
