# Generated by Django 3.1.1 on 2021-05-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_auto_20210526_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Dead_line',
            field=models.DateTimeField(null=True),
        ),
    ]
