# Generated by Django 3.1.1 on 2021-05-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_auto_20210526_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Dead_line',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
